version: "3"

services:
  db-zappts:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  app:
    build: .
    ports:
      - "3000:3000"
